version: "2"
services:
  webserver:
    image: docker pull php:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: test
      MYSQL_USER: admin  
      MYSQL_PASSWORD: admin123
      SITE_URL: database.cro4tmy0fvoq.ap-southeast-1.rds.amazonaws.com
    networks:
      - test

networks:
  test:
    external: true
